services:
  - type: web
    name: knowthee
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0
    envVars:
      - key: PYTHONUNBUFFERED
        value: true
      - key: OPENAI_API_KEY
        sync: false  # This indicates it should be set in the Render dashboard
    plan: starter  # You can change this based on your needs 